# Generated by Django 6.1.1 on 2026-09-24 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'Address must be at least 20 characters.')]),
        ),
    ]
