# Generated by Django 6.1.1 on 2026-09-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dog_friendly', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('dogs', models.PositiveIntegerField(default=0)),
                ('dog_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('nightly_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_nights', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_requests', models.TextField(blank=True)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BookingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_gallery/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='bookings.unit')),
            ],
        ),
    ]
