# Generated by Django 6.1.1 on 2026-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitgalleryimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='unitgalleryimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
