# Generated by Django 6.1.1 on 2026-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_unitgalleryimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='dog_friendly',
            new_name='dogs_allowed',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='base_price_per_night',
            new_name='price_per_night',
        ),
        migrations.AddField(
            model_name='unit',
            name='dog_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='unit',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='unit_main/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
