# Generated by Django 6.1.1 on 2026-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_dog_friendly_unit_dogs_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='max_guests',
            new_name='max_adults',
        ),
        migrations.AddField(
            model_name='unit',
            name='max_children',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
