# Generated by Django 6.1.1 on 2026-09-23 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_max_guests_unit_max_adults_unit_max_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
