# Generated by Django 6.1.1 on 2026-09-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_customer_email_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangerequest',
            name='request_type',
            field=models.CharField(choices=[('MODIFY', 'Modification'), ('CANCEL', 'Cancellation')], default='MODIFY', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingchangerequest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='bookings.booking'),
        ),
    ]
