# Generated by Django 6.1.1 on 2026-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingchangerequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchangerequest',
            name='requested_adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingchangerequest',
            name='requested_check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingchangerequest',
            name='requested_check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingchangerequest',
            name='requested_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingchangerequest',
            name='requested_dogs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingchangerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
