# Generated by Django 6.1.1 on 2026-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingchangerequest_requested_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingchangerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Accepted'), ('REJECTED', 'Declined')], default='OPEN', max_length=20),
        ),
    ]
