# Generated by Django 6.1.1 on 2026-09-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookingchangerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dog_charge_type',
            field=models.CharField(choices=[('PER_DOG_PER_STAY', 'Per dog per stay'), ('PER_STAY', 'Per stay')], default='PER_DOG_PER_STAY', max_length=20),
        ),
        migrations.CreateModel(
            name='UnitBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='bookings.unit')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('unit', 'date'), name='unique_unit_blocked_date')],
            },
        ),
    ]
